apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-app
  namespace: mlops
spec:
  replicas: 2                          
  selector:
    matchLabels:
      app: mlops-app
  template:
    metadata:
      labels:
        app: mlops-app
    spec:
      containers:
        - name: mlops-app
          image: anuj1303/mlops-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

          
          env:
            - name: DRIFT_THRESHOLD
              value: "0.3"
            - name: ALLOW_DRIFT
              value: "false"
            - name: FORCE_DRIFT
              value: "false"

          resources:
            requests:
              memory: "128Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mlops-app-hpa
  namespace: mlops
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mlops-app
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70