name: MLOps Automated Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pandas evidently
        env:
          ALLOW_DRIFT: "true"
            
            

      - name: Run Drift Analysis
        run: python generate_drift.py
        

      - name: Build Docker Image
        run: docker build -t mlops-app:latest .

      - name: Upload Drift Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mlops-drift-report
          path: drift_report.html

          # Triggering stable run with Python 3.12